# -*- coding: utf-8 -*-
"""simple_pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjFCBoDj0Ag06rjSy1O17Oi5-cTqEWjr
"""

import torch
import torch.nn as nn

model=nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

X=torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y=torch.tensor([[0.],[1.],[1.],[0.]])

"""**Loss Function and Optimizer**

*   MSELoss measures prediction error
*   Adam optimizer updates weights efficiently
"""

loss_fn=nn.MSELoss()
opt=torch.optim.Adam(model.parameters(),lr=0.01)

"""For each iteration:

1.   Clear
2.   List item


"""

for _ in range(1000):
  opt.zero_grad()
  loss=loss_fn(model(X),y)
  loss.backward()
  opt.step()

"""**Model Inference**

We print the model's predictions after training
"""

print(model(X))